Dynamic form script added and need ButtonTemplate connection
helpbuttons/hb-front pull request #74
Opened 2021-11-05 18:05 UTC by watchoutfreedom

Dynamic form script is working but we need to connect it with an store.emit call to the API and get the buttonTemplate data for the current network. Once we get that we can update the DynamicForm component with the model data (it has a model attribute that can be updated inside). This Dynamic form can be used both in the ButtonNew creation and in the search filters of the home to enable/disable search options.

2021-11-06 08:31 UTC, dukebody requested changes
Export the `DynamicForm` component and remove the `DynForm` one and associated mock data.

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +        //console.log("Select default: ", value);
this can be deleted

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +          //console.log("Checkbox: ", checked);
delete, along with other debug comments

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +const model = [
this was just mock data to be able to see an example rendered in a page. Delete it.

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +const DynamicForm = (props) => {
This is what should be exported in the file, and not the component at the end of the file which is just an example.

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +function DynForm() {
Don't export this component. It was just an example.

2021-11-06 08:31 UTC, dukebody commented on src/elements/DynForm/index.tsx
> +const DynamicForm = (props) => {
We might want to type the `props`, since the model for the form is relatively complex and will break if it doesn't contain the appropriate attributes.

2021-11-06 08:31 UTC, dukebody commented on src/pages/Profile/index.tsx
> +import DynForm from 'elements/DynForm'
Why do we import components that later are not used?

2021-11-09 02:17 UTC, merged

2021-11-09 02:21 UTC, watchoutfreedom commented on src/elements/DynForm/index.tsx
> +const DynamicForm = (props) => {
thank you, how would you do it? I thought model was the best way to specify different types of fields in the future (we may end up having images, articles, and other more complex elements in the form)

2021-11-09 02:21 UTC, watchoutfreedom commented on src/elements/DynForm/index.tsx
> +function DynForm() {
ok